version: '3'
services:
  app-server:
    image: 'visual-temp:latest'
    build: .
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - DATABASE_URL=postgres://postgres@postgres/postgres
    restart: always
    command: ./wait-for-postgres.sh postgres yarn start
    ports:
      - '38000:38000'
  postgres:
    image: 'postgres:10.0-alpine'
    deploy:
      resources:
        limits:
          memory: 0.5G
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/visual-temp-data
    volumes:
      - /data/visual-temp:/data
    ports:
      - '127.0.0.1:5432:5432'
